### PR TITLE
add tqdm disabling option

### LINKED ISSUE #688: progress bars should be optional
should be a way to disable the `tqdm` progress bars

### PR DESCRIPTION
**Pull request by maxwest-uw**
resolves #688 

also adds the progress bar to the lazy work unit reprojection changes (which weren't merged at the time of the original pr 😅 )

### CODE REVIEW

**Review by DinoBektesevic — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround. This all looks fine to me, but I do have one request. 

Can you make a global var in top-level init something like:
```
PROGRESS_BAR=True
```

and then make 

```
disable_progress=kbmod.PROGRESS_BAR
```

so that I can 

```
import kbmod
kbmod.PROGRESS_BARS = False
```

and turn them all off at once. 

Bonus points if you set the default value as:

```
PROGRESS_BARS = bool(os.environ.get("KB_PROGRESS_BARS", True)
```

so that I can also set the `KB_PROGRESS_BARS` env to a falsy value in the running scripts instead of having to repeat it in every task after import.

**Comment by maxwest-uw** [comment]
part one of your request (being able to set `PROGRESS_BAR` at runtime) doesn't seem to work, as the downstream import in `WorkUnit` only ever seems to load what it was initially

**Comment by DinoBektesevic** [comment]
Importing it will make a copy of the variable and then keep it in the module's global namespace. You have to get your values from where they're defined. I rejiggered the global variable access and removed some unused imports. This seems to work fine for me now, perhaps double check.

**Comment by maxwest-uw** [comment]
looks good to me (can I say that on my on pr? 😭  )

**Review by DinoBektesevic — APPROVED** [review]

**Pull request merged**
